server:
  port: 8082
myspcloud:
  item:
    url: http://127.0.0.1:8081/item/
spring:
  application:
    name: app-order
app-item:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
#开启hystrix断路器
feign:
  hystrix:
    enable: true
#eureka:
#  client:
#    service-url:
#      defautZone: http://127.0.0.1:8100/eureka
eureka:
  client:
    service-url:
      defaultZone: http://liwei:123456@127.0.0.1:8100/eureka/,http://liwei:123456@127.0.0.1:9100/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true  #将自己的ip地址注册到eureka服务中
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}###${server.port} #指定实列id
### 取应用名，注册到eureka

#server:
#  port: 8082 #服务端口
#myspcloud:
#  item:
#    url: http://127.0.0.1:8081/item/
####起个名字作为服务名称(该服务注册到eureka注册中心的名称，比如订单服务)
#spring:
#  application:
#    name: app-order
####服务注册到eureka注册中心的地址
#eureka:
#  client:
#    service-url:
#      defaultZone: http://127.0.0.1:8100/eureka
#    ###因为该应用为服务提供者，是eureka的一个客户端，需要注册到注册中心
#    register-with-eureka: true
#    ###是否需要从eureka上检索服务
#    fetch-registry: true