server:
  port: 8081 #服务端口
#  port: 8091 #服务端口

spring:
  application:
    name: app-item #取名，注册到注册中心

    # 服务注册到eureka中心的地址
eureka:
  client:
    service-url:
      defaultZone: http://liwei:123456@127.0.0.1:8100/eureka/,http://liwei:123456@127.0.0.1:9100/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}###${server.port} #指定实列id

