### 服务端口号
server:
#  port: 9100
  port: 8100

  # 服务mingcheng
spring:
  application:
    name: app-eureka-center
  security:
    basic:
      enable: true #开启基于Http basic的认证
    user:
      name: liwei #配置用户的账号信息
      password: 123456
eureka:
  instance:
    #注册中心地址
    hostname: 127.0.0.1

## 客户端调用地址
  client:

### 是否需要将自己注册到eureka服务中，自己本身就是注册中心，所以不需要
#    register-with-eureka: true
    register-with-eureka: false
### 是否需要从Eureka 中获取注册信息,因为自己为注册中心，不会在该应用中检索服务信息
#    fetch-registry: true
    fetch-registry: false
#    service-url:
#      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:8100/eureka
#      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:9100/eureka
  server:
    enable-self-preservation: false #禁用自我保护模式

